export const transactions = [
  {
    date: "02-03-2025",
    paymentType: "cash",
    location: "Pune",
    description: "Brownie",
    amount: 50,
    account: "expense",
  },
  {
    date: "02-03-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To lended people",
    amount: 300,
    account: "expense",
  },
  {
    date: "01-03-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner",
    amount: 78,
    account: "expense",
  },
  {
    date: "01-03-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Metro",
    amount: 30,
    account: "expense",
  },
  {
    date: "01-03-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snacks",
    amount: 67,
    account: "expense",
  },
  {
    date: "01-03-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From vicky",
    amount: 100,
    account: "saving",
  },
  {
    date: "01-03-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From dad",
    amount: 500,
    account: "income",
  },
  {
    date: "28-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Pizza",
    amount: 339.15,
    account: "expense",
  },
  {
    date: "28-02-2025",
    paymentType: "cash",
    location: "Indore",
    description: "From kumara",
    amount: 200,
    account: "saving",
  },
  {
    date: "27-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch",
    amount: 243,
    account: "expense",
  },
  {
    date: "27-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Tata Elexi",
    amount: 3000,
    account: "investment",
  },
  {
    date: "26-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snack",
    amount: 25,
    account: "expense",
  },
  {
    date: "26-02-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From dad",
    amount: 1500,
    account: "income",
  },
  {
    date: "26-02-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To karthi",
    amount: 100,
    account: "expense",
  },
  {
    date: "26-02-2025",
    paymentType: "mobile banking",
    location: "Jabalpur",
    description: "Pravesh",
    amount: 1700,
    account: "expense",
  },
  {
    date: "26-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snacks",
    amount: 40,
    account: "expense",
  },
  {
    date: "26-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Tea lights",
    amount: 84,
    account: "expense",
  },
  {
    date: "25-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Tea lights",
    amount: 33,
    account: "expense",
  },
  {
    date: "24-02-2025",
    paymentType: "cash",
    location: "Pune",
    description: "Toiletrires",
    amount: 303,
    account: "expense",
  },
  {
    date: "24-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Creamstone",
    amount: 289,
    account: "expense",
  },
  {
    date: "24-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Tamen",
    amount: 324.7,
    account: "expense",
  },
  {
    date: "23-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Hoodie for gobi",
    amount: 399,
    account: "expense",
  },
  {
    date: "23-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Eggs",
    amount: 83,
    account: "expense",
  },
  {
    date: "23-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Earphone",
    amount: 399,
    account: "expense",
  },
  {
    date: "22-02-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Auto to laxmi mills",
    amount: 120,
    account: "expense",
  },
  {
    date: "21-02-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "It better be worth it",
    amount: 1300,
    account: "expense",
  },
  {
    date: "21-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Adani solar",
    amount: 10000,
    account: "investment",
  },
  {
    date: "21-02-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Travel to koyambedu",
    amount: 138,
    account: "expense",
  },
  {
    date: "21-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Stuffs",
    amount: 336,
    account: "expense",
  },
  {
    date: "21-02-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Train cbe to chn",
    amount: 201.8,
    account: "expense",
  },
  {
    date: "20-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch",
    amount: 200,
    account: "expense",
  },
  {
    date: "19-02-2025",
    paymentType: "cash",
    location: "Pune",
    description: "Random stuff for drinks",
    amount: 111,
    account: "expense",
  },
  {
    date: "19-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snacks",
    amount: 250,
    account: "expense",
  },
  {
    date: "19-02-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Bus ticket",
    amount: 1575,
    account: "expense",
  },
  {
    date: "19-02-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Took from sbi",
    amount: 200,
    account: "expense",
  },
  {
    date: "19-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Ramen with gobi",
    amount: 380,
    account: "expense",
  },
  {
    date: "19-02-2025",
    paymentType: "card",
    location: "Nagpur",
    description: "Metro",
    amount: 60,
    account: "expense",
  },
  {
    date: "19-02-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To auto anna",
    amount: 50,
    account: "expense",
  },
  {
    date: "19-02-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "To egmore",
    amount: 270,
    account: "expense",
  },
  {
    date: "18-02-2025",
    paymentType: "cash",
    location: "Pune",
    description: "Kfc dinner",
    amount: 348,
    account: "expense",
  },
  {
    date: "17-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch",
    amount: 80,
    account: "expense",
  },
  {
    date: "16-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Side dishes",
    amount: 165,
    account: "expense",
  },
  {
    date: "16-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "FMC",
    amount: 4500,
    account: "investment",
  },
  {
    date: "16-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Kfc",
    amount: 475,
    account: "expense",
  },
  {
    date: "13-02-2025",
    paymentType: "mobile banking",
    location: "Jabalpur",
    description: "Games",
    amount: 100,
    account: "expense",
  },
  {
    date: "12-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner with aravind and buddies",
    amount: 491,
    account: "expense",
  },
  {
    date: "12-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Mirror",
    amount: 70,
    account: "expense",
  },
  {
    date: "12-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch",
    amount: 80,
    account: "expense",
  },
  {
    date: "12-02-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From dad",
    amount: 10000,
    account: "income",
  },
  {
    date: "11-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner with aravind",
    amount: 373,
    account: "expense",
  },
  {
    date: "10-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Kfc dinner",
    amount: 641,
    account: "expense",
  },
  {
    date: "08-02-2025",
    paymentType: "cash",
    location: "Indore",
    description: "From dad",
    amount: 1000,
    account: "income",
  },
  {
    date: "08-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Bean bag",
    amount: 2099,
    account: "expense",
  },
  {
    date: "07-02-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Auto to Gobi's place",
    amount: 214,
    account: "expense",
  },
  {
    date: "06-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Cakepark",
    amount: 125,
    account: "expense",
  },
  {
    date: "06-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "To kumara",
    amount: 150,
    account: "expense",
  },
  {
    date: "06-02-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "To chennai",
    amount: 1000,
    account: "expense",
  },
  {
    date: "06-02-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "Salary from dad",
    amount: 5000,
    account: "income",
  },
  {
    date: "06-02-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To gobi",
    amount: 1500,
    account: "expense",
  },
  {
    date: "06-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "FMC",
    amount: 23053,
    account: "investment",
  },
  {
    date: "04-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Shawarma",
    amount: 80,
    account: "expense",
  },
  {
    date: "03-02-2025",
    paymentType: "card",
    location: "Pune",
    description: "Good soup",
    amount: 50,
    account: "expense",
  },
  {
    date: "03-02-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To gowdham",
    amount: 150,
    account: "expense",
  },
  {
    date: "02-02-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Parotta",
    amount: 120,
    account: "expense",
  },
  {
    date: "02-02-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From dad",
    amount: 500,
    account: "income",
  },
  {
    date: "31-01-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Vnr to apk",
    amount: 50,
    account: "expense",
  },
  {
    date: "31-01-2025",
    paymentType: "cash",
    location: "Indore",
    description: "To vicky",
    amount: 200,
    account: "expense",
  },
  {
    date: "31-01-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "To ksr station",
    amount: 153,
    account: "expense",
  },
  {
    date: "30-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner",
    amount: 155,
    account: "expense",
  },
  {
    date: "30-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Cycle gap",
    amount: 120,
    account: "expense",
  },
  {
    date: "30-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Brunch",
    amount: 105,
    account: "expense",
  },
  {
    date: "29-01-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Rapido to pg",
    amount: 44,
    account: "expense",
  },
  {
    date: "29-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "HDFC",
    amount: 20000,
    account: "investment",
  },
  {
    date: "29-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "Sent to barath",
    amount: 100,
    account: "expense",
  },
  {
    date: "28-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Banana",
    amount: 10,
    account: "expense",
  },
  {
    date: "28-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with company",
    amount: 138,
    account: "expense",
  },
  {
    date: "27-01-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Rapido to pg",
    amount: 43,
    account: "expense",
  },
  {
    date: "27-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To vicky",
    amount: 300,
    account: "expense",
  },
  {
    date: "27-01-2025",
    paymentType: "cash",
    location: "Indore",
    description: "To vishnu",
    amount: 100,
    account: "expense",
  },
  {
    date: "27-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Zinger box meal",
    amount: 279,
    account: "expense",
  },
  {
    date: "27-01-2025",
    paymentType: "cash",
    location: "Indore",
    description: "From vicky",
    amount: 300,
    account: "saving",
  },
  {
    date: "27-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From dad",
    amount: 1500,
    account: "income",
  },
  {
    date: "26-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snacks",
    amount: 115,
    account: "expense",
  },
  {
    date: "26-01-2025",
    paymentType: "card",
    location: "Indore",
    description: "Vishnu 100 gowdham 25",
    amount: 125,
    account: "saving",
  },
  {
    date: "26-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Paani poori",
    amount: 25,
    account: "expense",
  },
  {
    date: "25-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Kfc date with myself",
    amount: 259,
    account: "expense",
  },
  {
    date: "25-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lemon tea",
    amount: 18,
    account: "expense",
  },
  {
    date: "25-01-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Train to vnr",
    amount: 325,
    account: "expense",
  },
  {
    date: "24-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snack",
    amount: 40,
    account: "expense",
  },
  {
    date: "24-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with company",
    amount: 133,
    account: "expense",
  },
  {
    date: "23-01-2025",
    paymentType: "cash",
    location: "Pune",
    description: "Pepsi",
    amount: 40,
    account: "expense",
  },
  {
    date: "23-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner",
    amount: 465,
    account: "expense",
  },
  {
    date: "23-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Sent to vicky",
    amount: 300,
    account: "expense",
  },
  {
    date: "23-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch",
    amount: 302,
    account: "expense",
  },
  {
    date: "23-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From vicky",
    amount: 310,
    account: "saving",
  },
  {
    date: "23-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snacks with preethi and azar",
    amount: 176,
    account: "expense",
  },
  {
    date: "20-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Nestle India",
    amount: 20000,
    account: "investment",
  },
  {
    date: "23-01-2025",
    paymentType: "mobile banking",
    location: "Jabalpur",
    description: "Badminton",
    amount: 200,
    account: "expense",
  },
  {
    date: "23-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From dad",
    amount: 2000,
    account: "income",
  },
  {
    date: "21-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with company",
    amount: 188,
    account: "expense",
  },
  {
    date: "21-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snacks",
    amount: 37,
    account: "expense",
  },
  {
    date: "21-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From vicky",
    amount: 200,
    account: "saving",
  },
  {
    date: "19-01-2025",
    paymentType: "cash",
    location: "Pune",
    description: "Lunch + chocolate for preethi",
    amount: 171,
    account: "expense",
  },
  {
    date: "18-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner",
    amount: 301.15,
    account: "expense",
  },
  {
    date: "18-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snack with preethi",
    amount: 59,
    account: "expense",
  },
  {
    date: "18-01-2025",
    paymentType: "card",
    location: "Pune",
    description: "Lunch with company",
    amount: 148,
    account: "expense",
  },
  {
    date: "18-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To kumara",
    amount: 200,
    account: "expense",
  },
  {
    date: "18-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From dad",
    amount: 1000,
    account: "income",
  },
  {
    date: "17-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Eve snack",
    amount: 100,
    account: "expense",
  },
  {
    date: "15-01-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Bus to Bangalore",
    amount: 1365,
    account: "expense",
  },
  {
    date: "15-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From dad",
    amount: 1500,
    account: "income",
  },
  {
    date: "15-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snacks",
    amount: 70,
    account: "expense",
  },
  {
    date: "14-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "Kumara",
    amount: 170,
    account: "saving",
  },
  {
    date: "14-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "Siva + 100 cash",
    amount: 70,
    account: "saving",
  },
  {
    date: "14-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "TCS",
    amount: 13120,
    account: "investment",
  },
  {
    date: "14-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "Gundan + prasanna",
    amount: 340,
    account: "saving",
  },
  {
    date: "14-01-2025",
    paymentType: "cash",
    location: "Indore",
    description: "Dinesh and maddy + 100 cash",
    amount: 240,
    account: "saving",
  },
  {
    date: "14-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From gowdham",
    amount: 340,
    account: "saving",
  },
  {
    date: "14-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch pongal",
    amount: 1530,
    account: "expense",
  },
  {
    date: "13-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner",
    amount: 66,
    account: "expense",
  },
  {
    date: "13-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From dad",
    amount: 1000,
    account: "income",
  },
  {
    date: "13-01-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Rapido to pg",
    amount: 43,
    account: "expense",
  },
  {
    date: "12-01-2025",
    paymentType: "card",
    location: "Indore",
    description: "Recharge by gowdham",
    amount: 479,
    account: "expense",
  },
  {
    date: "12-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Pizza",
    amount: 301.75,
    account: "expense",
  },
  {
    date: "12-01-2025",
    paymentType: "cash",
    location: "Indore",
    description: "From kumara",
    amount: 200,
    account: "saving",
  },
  {
    date: "11-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with not preethi",
    amount: 135.5,
    account: "expense",
  },
  {
    date: "10-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Friday snacks with preethi gang",
    amount: 106,
    account: "expense",
  },
  {
    date: "08-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From gowdham",
    amount: 260,
    account: "saving",
  },
  {
    date: "08-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with gowdham",
    amount: 535.3,
    account: "expense",
  },
  {
    date: "08-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Rent",
    amount: 4580,
    account: "expense",
  },
  {
    date: "07-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Coffee + biscuit",
    amount: 15,
    account: "expense",
  },
  {
    date: "06-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From barath and shakur",
    amount: 440,
    account: "saving",
  },
  {
    date: "06-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Ketch up",
    amount: 20,
    account: "expense",
  },
  {
    date: "06-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner with roommate",
    amount: 877.81,
    account: "expense",
  },
  {
    date: "06-01-2025",
    paymentType: "card",
    location: "Pune",
    description: "Bingo",
    amount: 10,
    account: "expense",
  },
  {
    date: "06-01-2025",
    paymentType: "cash",
    location: "Nagpur",
    description: "Rapido to pg",
    amount: 42,
    account: "expense",
  },
  {
    date: "05-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "McDonald's with company",
    amount: 211,
    account: "expense",
  },
  {
    date: "05-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "Lended money returned to vishnu",
    amount: 40,
    account: "expense",
  },
  {
    date: "05-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "Lended money returned to kumara",
    amount: 30,
    account: "expense",
  },
  {
    date: "05-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Jan 2nd with shakur and barath",
    amount: 354,
    account: "expense",
  },
  {
    date: "05-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To gobi 1st 1-4th",
    amount: 500,
    account: "expense",
  },
  {
    date: "05-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To abijith and to vicky lend money returned",
    amount: 500,
    account: "expense",
  },
  {
    date: "05-01-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Refund for bus ticket",
    amount: 60,
    account: "expense",
  },
  {
    date: "05-01-2025",
    paymentType: "cash",
    location: "Pune",
    description: "Lunch with company",
    amount: 388,
    account: "expense",
  },
  {
    date: "05-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Castrol",
    amount: 12780,
    account: "investment",
  },
  {
    date: "04-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Arrear and reval fee",
    amount: 1400,
    account: "expense",
  },
  {
    date: "04-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Salary",
    amount: 8000,
    account: "income",
  },
  {
    date: "04-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with company",
    amount: 106,
    account: "expense",
  },
  {
    date: "04-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To vicky",
    amount: 80,
    account: "expense",
  },
  {
    date: "04-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Sent to preethi",
    amount: 107,
    account: "expense",
  },
  {
    date: "03-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dairy milk",
    amount: 10,
    account: "expense",
  },
  {
    date: "03-01-2025",
    paymentType: "card",
    location: "Indore",
    description: "From barath",
    amount: 201,
    account: "saving",
  },
  {
    date: "03-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From gpay",
    amount: 5,
    account: "saving",
  },
  {
    date: "03-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From shakur",
    amount: 140,
    account: "saving",
  },
  {
    date: "03-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch unlimited nv",
    amount: 300,
    account: "expense",
  },
  {
    date: "03-01-2025",
    paymentType: "cash",
    location: "Indore",
    description: "From abi",
    amount: 300,
    account: "saving",
  },
  {
    date: "02-01-2025",
    paymentType: "mobile banking",
    location: "Indore",
    description: "Tablet to gowdham",
    amount: 8,
    account: "expense",
  },
  {
    date: "02-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner with barath",
    amount: 200,
    account: "expense",
  },
  {
    date: "02-01-2025",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Train to vnr",
    amount: 725,
    account: "expense",
  },
  {
    date: "01-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snacks",
    amount: 85,
    account: "expense",
  },
  {
    date: "01-01-2025",
    paymentType: "mobile banking",
    location: "Pune",
    description: "From dad",
    amount: 1000,
    account: "income",
  },
  {
    date: "30-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "To barath",
    amount: 20,
    account: "expense",
  },
  {
    date: "30-12-2024",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Pg to office",
    amount: 43,
    account: "expense",
  },
  {
    date: "30-12-2024",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From kumara",
    amount: 30,
    account: "saving",
  },
  {
    date: "30-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Horlicks + kolakattai",
    amount: 25,
    account: "expense",
  },
  {
    date: "30-12-2024",
    paymentType: "card",
    location: "Nagpur",
    description: "Bommasandra to pg",
    amount: 199,
    account: "expense",
  },
  {
    date: "30-12-2024",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From Deepak",
    amount: 250,
    account: "saving",
  },
  {
    date: "30-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Water",
    amount: 20,
    account: "expense",
  },
  {
    date: "30-12-2024",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From abi",
    amount: 20,
    account: "saving",
  },
  {
    date: "30-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Castrol",
    amount: 12780,
    account: "investment",
  },
  {
    date: "30-12-2024",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Rapido + toll",
    amount: 286,
    account: "expense",
  },
  {
    date: "30-12-2024",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From Deepak",
    amount: 250,
    account: "saving",
  },
  {
    date: "28-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Coffee and thattai",
    amount: 14,
    account: "expense",
  },
  {
    date: "27-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with barath",
    amount: 115,
    account: "expense",
  },
  {
    date: "27-12-2024",
    paymentType: "card",
    location: "Indore",
    description: "From vicky",
    amount: 80,
    account: "saving",
  },
  {
    date: "27-12-2024",
    paymentType: "cash",
    location: "Indore",
    description: "From ganesan",
    amount: 40,
    account: "saving",
  },
  {
    date: "27-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Coconut water with stu",
    amount: 50,
    account: "expense",
  },
  {
    date: "25-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner with barath",
    amount: 504,
    account: "expense",
  },
  {
    date: "25-12-2024",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Cab",
    amount: 306,
    account: "expense",
  },
  {
    date: "25-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Books",
    amount: 400,
    account: "expense",
  },
  {
    date: "25-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Corn",
    amount: 30,
    account: "expense",
  },
  {
    date: "25-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Water",
    amount: 30,
    account: "expense",
  },
  {
    date: "25-12-2024",
    paymentType: "card",
    location: "Pune",
    description: "Milk with bharath",
    amount: 40,
    account: "expense",
  },
  {
    date: "24-12-2024",
    paymentType: "mobile banking",
    location: "Jabalpur",
    description: "Beer",
    amount: 150,
    account: "expense",
  },
  {
    date: "24-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with company",
    amount: 262,
    account: "expense",
  },
  {
    date: "23-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lemon tea with company",
    amount: 15,
    account: "expense",
  },
  {
    date: "23-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Puffs and coffee",
    amount: 32,
    account: "expense",
  },
  {
    date: "21-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner with barath",
    amount: 239,
    account: "expense",
  },
  {
    date: "21-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Puffs",
    amount: 25,
    account: "expense",
  },
  {
    date: "21-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Bun",
    amount: 18,
    account: "expense",
  },
  {
    date: "20-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Milk with bharath",
    amount: 80,
    account: "expense",
  },
  {
    date: "20-12-2024",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Taxi",
    amount: 80,
    account: "expense",
  },
  {
    date: "20-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snacks",
    amount: 20,
    account: "expense",
  },
  {
    date: "20-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Water",
    amount: 20,
    account: "expense",
  },
  {
    date: "20-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "LIC",
    amount: 2880,
    account: "investment",
  },
  {
    date: "20-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Lunch with barath",
    amount: 85,
    account: "expense",
  },
  {
    date: "20-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Milk with bharath",
    amount: 40,
    account: "expense",
  },
  {
    date: "19-12-2024",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To siva",
    amount: 100,
    account: "expense",
  },
  {
    date: "18-12-2024",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To kumara",
    amount: 100,
    account: "expense",
  },
  {
    date: "18-12-2024",
    paymentType: "mobile banking",
    location: "Indore",
    description: "To abijith",
    amount: 200,
    account: "expense",
  },
  {
    date: "18-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "To rahul",
    amount: 113,
    account: "expense",
  },
  {
    date: "18-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "From dad",
    amount: 1000,
    account: "income",
  },
  {
    date: "18-12-2024",
    paymentType: "mobile banking",
    location: "Indore",
    description: "Lended money",
    amount: 400,
    account: "saving",
  },
  {
    date: "18-12-2024",
    paymentType: "cash",
    location: "Jabalpur",
    description: "Spiderman",
    amount: 363.72,
    account: "expense",
  },
  {
    date: "18-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch",
    amount: 160,
    account: "expense",
  },
  {
    date: "17-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Milk with bharath",
    amount: 70,
    account: "expense",
  },
  {
    date: "17-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with company",
    amount: 110,
    account: "expense",
  },
  {
    date: "17-12-2024",
    paymentType: "mobile banking",
    location: "Indore",
    description: "Gave to gowdham",
    amount: 50,
    account: "expense",
  },
  {
    date: "16-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Egg",
    amount: 30,
    account: "expense",
  },
  {
    date: "16-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Panipoori",
    amount: 20,
    account: "expense",
  },
  {
    date: "16-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch",
    amount: 30,
    account: "expense",
  },
  {
    date: "16-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Milk with bharath",
    amount: 110,
    account: "expense",
  },
  {
    date: "14-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch",
    amount: 40,
    account: "expense",
  },
  {
    date: "14-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snacks",
    amount: 75,
    account: "expense",
  },
  {
    date: "14-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Panipoori",
    amount: 80,
    account: "expense",
  },
  {
    date: "14-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snacks",
    amount: 74,
    account: "expense",
  },
  {
    date: "14-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Milk with bharath",
    amount: 65,
    account: "expense",
  },
  {
    date: "12-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Milk with bharath",
    amount: 25,
    account: "expense",
  },
  {
    date: "11-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "From dad",
    amount: 1000,
    account: "income",
  },
  {
    date: "11-12-2024",
    paymentType: "mobile banking",
    location: "Indore",
    description: "From stu",
    amount: 240,
    account: "saving",
  },
  {
    date: "10-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Shopping",
    amount: 241,
    account: "expense",
  },
  {
    date: "10-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Momos",
    amount: 195,
    account: "expense",
  },
  {
    date: "09-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snack with bharath",
    amount: 40,
    account: "expense",
  },
  {
    date: "09-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with company",
    amount: 280,
    account: "expense",
  },
  {
    date: "09-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Milk with bharath",
    amount: 25,
    account: "expense",
  },
  {
    date: "09-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Breakfast with stu",
    amount: 110,
    account: "expense",
  },
  {
    date: "08-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Lunch with stu",
    amount: 100,
    account: "expense",
  },
  {
    date: "08-12-2024",
    paymentType: "Cash",
    location: "Pune",
    description: "Grand Hyatt",
    amount: 1120.72,
    account: "expense",
  },
  {
    date: "08-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Milk",
    amount: 10,
    account: "expense",
  },
  {
    date: "07-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Milk with bharath",
    amount: 25,
    account: "expense",
  },
  {
    date: "07-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Horlicks",
    amount: 15,
    account: "expense",
  },
  {
    date: "06-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Milk with bharath",
    amount: 25,
    account: "expense",
  },
  {
    date: "06-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Shoe",
    amount: 500,
    account: "expense",
  },
  {
    date: "06-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Cap",
    amount: 140,
    account: "expense",
  },
  {
    date: "06-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Lunch with stu",
    amount: 150,
    account: "expense",
  },
  {
    date: "05-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Milk with bharath",
    amount: 25,
    account: "expense",
  },
  {
    date: "05-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Full hand and a hoodie",
    amount: 1800,
    account: "expense",
  },
  {
    date: "05-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Rent",
    amount: 4800,
    account: "expense",
  },
  {
    date: "05-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "From dad",
    amount: 8000,
    account: "income",
  },
  {
    date: "04-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Dinner",
    amount: 324,
    account: "expense",
  },
  {
    date: "04-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Snack",
    amount: 65,
    account: "expense",
  },
  {
    date: "04-12-2024",
    paymentType: "cash",
    location: "Indore",
    description: "For company",
    amount: 30,
    account: "expense",
  },
  {
    date: "04-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Breakfast",
    amount: 200,
    account: "expense",
  },
  {
    date: "03-12-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Milk with bharath",
    amount: 25,
    account: "expense",
  },
  {
    date: "03-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Belt",
    amount: 130,
    account: "expense",
  },
  {
    date: "03-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Mask",
    amount: 20,
    account: "expense",
  },
  {
    date: "03-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snack",
    amount: 40,
    account: "expense",
  },
  {
    date: "03-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "From dad",
    amount: 1000,
    account: "income",
  },
  {
    date: "02-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Ice cream",
    amount: 504,
    account: "expense",
  },
  {
    date: "02-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Vadapaav",
    amount: 75,
    account: "expense",
  },
  {
    date: "01-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Showergel",
    amount: 196,
    account: "expense",
  },
  {
    date: "01-12-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with company",
    amount: 160,
    account: "expense",
  },
  {
    date: "30-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Bharath birthday",
    amount: 115,
    account: "expense",
  },
  {
    date: "30-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with company",
    amount: 128,
    account: "expense",
  },
  {
    date: "30-11-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Breakfast",
    amount: 70,
    account: "expense",
  },
  {
    date: "29-11-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Lunch with company",
    amount: 40,
    account: "expense",
  },
  {
    date: "29-11-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Dinner",
    amount: 50,
    account: "expense",
  },
  {
    date: "29-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Panipoori",
    amount: 40,
    account: "expense",
  },
  {
    date: "29-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Breakfast",
    amount: 40,
    account: "expense",
  },
  {
    date: "28-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snack",
    amount: 94,
    account: "expense",
  },
  {
    date: "28-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Zomato",
    amount: 269.4,
    account: "expense",
  },
  {
    date: "27-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner with gowdham",
    amount: 120,
    account: "expense",
  },
  {
    date: "27-11-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Dinner with gowdham",
    amount: 130,
    account: "expense",
  },
  {
    date: "27-11-2024",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Rapido",
    amount: 35,
    account: "expense",
  },
  {
    date: "27-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with company",
    amount: 75,
    account: "expense",
  },
  {
    date: "27-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "From dad",
    amount: 2000,
    account: "income",
  },
  {
    date: "27-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Breakfast",
    amount: 30,
    account: "expense",
  },
  {
    date: "26-11-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Beer",
    amount: 150,
    account: "expense",
  },
  {
    date: "26-11-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Snack",
    amount: 102,
    account: "expense",
  },
  {
    date: "26-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Panipoori",
    amount: 40,
    account: "expense",
  },
  {
    date: "26-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Cashback",
    amount: 3,
    account: "saving",
  },
  {
    date: "26-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with company",
    amount: 150,
    account: "expense",
  },
  {
    date: "26-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Breakfast",
    amount: 60,
    account: "expense",
  },
  {
    date: "25-11-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Lunch with company",
    amount: 145,
    account: "expense",
  },
  {
    date: "25-11-2024",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Rapido",
    amount: 58,
    account: "expense",
  },
  {
    date: "25-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner",
    amount: 95,
    account: "expense",
  },
  {
    date: "24-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Snack",
    amount: 15,
    account: "expense",
  },
  {
    date: "24-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner",
    amount: 70,
    account: "expense",
  },
  {
    date: "24-11-2024",
    paymentType: "cash",
    location: "Pune",
    description: "Panipoori",
    amount: 20,
    account: "expense",
  },
  {
    date: "24-11-2024",
    paymentType: "mobile banking",
    location: "Nagpur",
    description: "Rapido",
    amount: 58,
    account: "expense",
  },
  {
    date: "23-11-2024",
    paymentType: "cash",
    location: "Nagpur",
    description: "Rapido",
    amount: 50,
    account: "expense",
  },
  {
    date: "23-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner",
    amount: 179,
    account: "expense",
  },
  {
    date: "22-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Dinner",
    amount: 90,
    account: "expense",
  },
  {
    date: "22-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch with company",
    amount: 97,
    account: "expense",
  },
  {
    date: "21-11-2024",
    paymentType: "cash",
    location: "Nagpur",
    description: "Rapido",
    amount: 130,
    account: "expense",
  },
  {
    date: "21-11-2024",
    paymentType: "mobile banking",
    location: "Pune",
    description: "Lunch",
    amount: 875,
    account: "expense",
  },
  {
    date: "21-11-2024",
    paymentType: "mobile banking",
    location: "Indore",
    description: "Got from gobi",
    amount: 2000,
    account: "saving",
  },
];
